import{SIZE,ITEMS,createGame,move,useItem,descend,visible,validSave}from './engine.js';
const $=id=>document.getElementById(id),KEY='akari-save-v1',RECORD='akari-record-v1';let state,overview=false,record={runs:0,best:1,wins:0},saveOK=true,notified=false,first=false,corrupt=false;
try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw);if(!validSave(parsed))throw Error('invalid');state=parsed}else first=true;const r=JSON.parse(localStorage.getItem(RECORD));if(r&&['runs','best','wins'].every(k=>Number.isFinite(r[k])))record=r}catch{corrupt=true}
state??=createGame();
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));localStorage.setItem(RECORD,JSON.stringify(record));saveOK=true}catch{saveOK=false}$('save-status').textContent=saveOK?'端末に自動保存済み':'保存できません：設定を確認してください'}
const canvas=$('map'),ctx=canvas.getContext('2d');
function draw(){const width=canvas.clientWidth,height=canvas.clientHeight,dpr=Math.min(window.devicePixelRatio||1,3);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#0b141a';ctx.fillRect(0,0,width,height);const cols=overview?SIZE:13,rows=overview?SIZE:11,tile=Math.min(width/cols,height/rows),ox=(width-cols*tile)/2,oy=(height-rows*tile)/2,left=overview?0:state.p.x-6,top=overview?0:state.p.y-5,vis=visible(state);const pos=(x,y)=>[ox+(x-left+.5)*tile,oy+(y-top+.5)*tile];
for(let ry=0;ry<rows;ry++)for(let rx=0;rx<cols;rx++){const x=left+rx,y=top+ry,k=y*SIZE+x;if(x<0||y<0||x>=SIZE||y>=SIZE||!state.seen[k])continue;const v=vis.has(k),px=ox+rx*tile,py=oy+ry*tile;ctx.fillStyle=state.map[k]?(v?((x+y)%2?'#24383d':'#263b40'):'#17262c'):(v?'#38484a':'#202e32');ctx.fillRect(px+1,py+1,tile-2,tile-2);if(!state.map[k]){ctx.fillStyle=v?'#4a5b58':'#293c3e';ctx.fillRect(px+1,py+1,tile-2,Math.max(1,tile*.12))}else if(v&&!overview){ctx.fillStyle='#3b5050';ctx.fillRect(px+tile*.25,py+tile*.7,2,2)}}
function glyph(x,y,text,color,scale=.68,force=false){const k=y*SIZE+x;if(!force&&!vis.has(k))return;if(x<left||x>=left+cols||y<top||y>=top+rows)return;const [px,py]=pos(x,y);ctx.fillStyle=color;ctx.font=`${Math.floor(tile*scale)}px -apple-system, sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,px,py+1)}
if(state.seen[state.stairs.y*SIZE+state.stairs.x])glyph(state.stairs.x,state.stairs.y,state.floor===10?'✦':'▤','#e6bc75',.78,true);
for(const t of state.traps)if(t.revealed)glyph(t.x,t.y,'×','#c18b7e');for(const i of state.items)glyph(i.x,i.y,ITEMS[i.type]?.glyph||({gold:'●',weapon:'†',armor:'⬡'}[i.type]),ITEMS[i.type]?.color||'#e6bc75',.6);
for(const e of state.enemies){glyph(e.x,e.y,e.type==='鬼火'?'火':e.type==='迷い鼠'?'鼠':'苔',e.type==='鬼火'?'#d3a4ef':e.type==='迷い鼠'?'#e7a398':'#a3ca99',.55);if(vis.has(e.y*SIZE+e.x)&&!overview){const [px,py]=pos(e.x,e.y);ctx.fillStyle='#bd7970';ctx.fillRect(px-tile*.25,py+tile*.36,tile*.5,2)}}const [px,py]=pos(state.p.x,state.p.y);ctx.shadowColor='#e6bc75';ctx.shadowBlur=overview?0:14;ctx.fillStyle='#e6bc75';ctx.beginPath();ctx.arc(px,py,tile*.24,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#fff0cb';ctx.lineWidth=1.5;ctx.stroke();ctx.fillStyle='#25333a';ctx.fillRect(px-tile*.07,py-tile*.09,tile*.14,tile*.18);
canvas.setAttribute('aria-label',`地下${state.floor}階。生命${state.p.hp}/${state.p.maxHp}。周囲の敵${state.enemies.filter(e=>vis.has(e.y*SIZE+e.x)).length}体。`)}
function render(){const p=state.p;$('floor').innerHTML=`B${state.floor}<span>F</span>`;$('hp').textContent=`${p.hp} / ${p.maxHp}`;$('level').textContent=`Lv.${p.level}`;$('hpbar').style.width=`${p.hp/p.maxHp*100}%`;$('hpbar').style.background=p.hp/p.maxHp<.3?'#e69887':'#9dd1bd';$('hunger').textContent=`満腹 ${p.food}%`;$('power').textContent=`攻 ${5+p.level*2+p.weapon} / 守 ${p.armor}`;$('turn').textContent=`第 ${state.turn} 手`;$('area').textContent=state.floor<4?'苔むす回廊':state.floor<7?'忘れられた祠':'灯の深淵';$('bagcount').textContent=`${state.bag.length}/12`;$('stairlabel').textContent=state.floor===10?'灯を持ち帰る':'階段を降りる';$('stairs').disabled=state.status!=='playing'||state.p.x!==state.stairs.x||state.p.y!==state.stairs.y;$('log').replaceChildren(...state.logs.slice(0,3).map(t=>{const p=document.createElement('p');p.textContent=t;return p}));draw();if(state.status!=='playing'&&!notified){notified=true;showEnd()}}
function act(fn){if($('modal').open||state.status!=='playing')return;const acted=fn();if(acted&&navigator.vibrate)navigator.vibrate(8);record.best=Math.max(record.best,state.floor);if(state.status!=='playing'&&!state.recorded){state.recorded=true;record.runs++;if(state.status==='won')record.wins++}save();render()}
function modal(html){$('modalbody').innerHTML=html;if(!$('modal').open)$('modal').showModal()}
function close(){$('modal').close()}
function showBag(){modal('<h2>道具袋 <small style="font-size:14px">'+state.bag.length+' / 12</small></h2><p>道具を使うと一手進み、敵も動きます。</p><div id="items"></div>');if(!state.bag.length)$('items').textContent='道具はありません。迷宮を探してみよう。';state.bag.forEach((type,i)=>{const item=ITEMS[type],row=document.createElement('div');row.className='item';row.innerHTML=`<span style="font-size:25px;color:${item.color}">${item.glyph}</span><div><strong>${item.name}</strong><small>${item.desc}</small></div><button ${state.status!=='playing'?'disabled':''}>使う</button>`;row.querySelector('button').onclick=()=>{close();act(()=>useItem(state,i))};$('items').append(row)})}
function showHelp(){modal(`<h2>一歩、一手、灯の先へ。</h2><p>地下10階に眠る「帰り灯」を持ち帰ろう。倒れると、その冒険の道具と成長は失われます。</p><p><kbd>方向ボタン</kbd>：8方向に移動。敵に向かうと攻撃。壁の角は斜めに抜けられません。<br><kbd>待つ</kbd>：一手待機。6手ごとに生命が1回復。<br><kbd>道具袋</kbd>：回復・食事・雷・ワープ。<br><kbd>階段</kbd>：上に乗ってからボタンで進む。</p><p>4手ごとに満腹度が1減り、0になると毎手ダメージ。道具は踏むと拾います。刀と護符は自動で装備。敵を倒すと成長します。</p><p>地図の上下左右をタップ、またはスワイプでも移動できます。PCでは矢印 / HJKL、YUBNで斜め、Spaceで待機。</p><p>iPhone：Safariの共有メニューから「ホーム画面に追加」。初回に「オフライン準備完了」が出てから、通信なしでも遊べます。</p><p>最高到達：地下${record.best}階 ／ 帰還 ${record.wins}回<br>冒険は一手ごとに端末へ保存。ブラウザのデータ削除で消えるため、必要なら書き出してください。同時に複数タブで遊ばないでください。</p><button class="textbtn" id="export">セーブを書き出す</button><button class="textbtn" id="import">セーブを読み込む</button><input id="file" type="file" accept="application/json,.json" hidden><button class="textbtn danger" id="restart">新しい冒険を始める</button><button class="primary" id="play">迷宮へ戻る</button>`);$('play').onclick=close;$('restart').onclick=confirmRestart;$('export').onclick=()=>{const blob=new Blob([JSON.stringify({state,record})],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='akari-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)};$('import').onclick=()=>$('file').click();$('file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>1000000)throw Error();const data=JSON.parse(await file.text());if(!validSave(data.state))throw Error();modal('<h2>冒険を読み込む</h2><p>現在の冒険を、選択したセーブで置き換えます。</p><button class="primary" id="load">置き換える</button><button class="textbtn" id="cancel">やめる</button>');$('cancel').onclick=showHelp;$('load').onclick=()=>{state=data.state;notified=false;close();save();render()}}catch{modal('<h2>読み込めませんでした</h2><p>灯の迷宮の有効なセーブファイルを選んでください。</p><button class="primary" id="back">戻る</button>');$('back').onclick=showHelp}}}
function confirmRestart(){modal('<h2>新しい冒険へ</h2><p>現在の冒険を終了します。道具とレベルは最初に戻ります。最高到達階と帰還記録は残ります。</p><button class="primary" id="new">新しく始める</button><button class="textbtn" id="cancel">続きに戻る</button>');$('new').onclick=newGame;$('cancel').onclick=close}
function newGame(){state=createGame();overview=false;notified=false;close();save();render()}
function showEnd(){modal(`<h2>${state.status==='won'?'灯は、ふたたび地上へ。':'消えた灯の、その先へ。'}</h2><p>${state.status==='won'?'帰り灯を持ち帰り、迷宮を踏破しました。':'この冒険は終わりました。新しい迷宮が、次の一歩を待っています。'}</p><p>地下${state.floor}階 ／ ${state.turn}手<br>Lv.${state.p.level} ／ 討伐 ${state.kills}体 ／ ${state.gold}銭</p><button class="primary" id="again">もう一度、迷宮へ</button><button class="textbtn" id="inspect">最後の地図を見る</button>`);$('again').onclick=newGame;$('inspect').onclick=close}
document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>act(()=>move(state,...b.dataset.move.split(',').map(Number))));document.querySelector('[data-action="wait"]').onclick=()=>act(()=>move(state,0,0));$('stairs').onclick=()=>act(()=>descend(state));$('bag').onclick=showBag;$('help').onclick=showHelp;$('close').onclick=close;$('overview').onclick=()=>{overview=!overview;$('overview').textContent=overview?'周辺図 ↙':'全体図 ↗';draw()};
const keys={ArrowUp:[0,-1],ArrowDown:[0,1],ArrowLeft:[-1,0],ArrowRight:[1,0],h:[-1,0],j:[0,1],k:[0,-1],l:[1,0],y:[-1,-1],u:[1,-1],b:[-1,1],n:[1,1],' ':[0,0]};document.addEventListener('keydown',e=>{if($('modal').open||e.ctrlKey||e.metaKey||e.altKey)return;if(keys[e.key]){e.preventDefault();if(!e.repeat)act(()=>move(state,...keys[e.key]))}});
let pointer;canvas.addEventListener('pointerdown',e=>{pointer={x:e.clientX,y:e.clientY,id:e.pointerId};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointercancel',()=>pointer=null);canvas.addEventListener('pointerup',e=>{if(!pointer||pointer.id!==e.pointerId)return;let dx=e.clientX-pointer.x,dy=e.clientY-pointer.y;pointer=null;if(overview)return;if(Math.hypot(dx,dy)<15){const r=canvas.getBoundingClientRect();dx=e.clientX-r.left-r.width/2;dy=e.clientY-r.top-r.height/2;if(Math.hypot(dx,dy)<15)return}const angle=Math.atan2(dy,dx),oct=Math.round(angle/(Math.PI/4));act(()=>move(state,Math.round(Math.cos(oct*Math.PI/4)),Math.round(Math.sin(oct*Math.PI/4))))});
new ResizeObserver(draw).observe(canvas);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')save()});window.addEventListener('pagehide',save);save();render();if(first) {modal('<h2>灯の迷宮</h2><p>足を踏み出すたび、迷宮も動き出す。<br>地下10階の「帰り灯」を探す冒険へ。</p><p>方向ボタンで移動。敵の方向へ進むと攻撃。危なくなったら道具袋から癒やし草を使おう。</p><button class="primary" id="begin">灯をともす</button>');$('begin').onclick=close}if(corrupt){modal('<h2>保存データを確認できません</h2><p>新しい冒険を準備しました。書き出したセーブがあれば「?」から読み込めます。</p><button class="primary" id="begin">迷宮へ</button>');$('begin').onclick=close}
if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js').then(()=>navigator.serviceWorker.ready).then(()=>{$('offline').textContent='オフライン準備完了'}).catch(()=>{$('offline').textContent='オフライン準備失敗・再読込してください'})}else $('offline').textContent='この環境はオフライン非対応';
