import test from 'node:test';import assert from 'node:assert/strict';import{SIZE,createGame,generate,move,useItem,dropItem,descend,validSave}from'../engine.js';
test('100 generated floors are connected; entities and saves are valid',()=>{for(let i=0;i<100;i++){const s=createGame();s.floor=i%10+1;generate(s);assert.ok(validSave(s));const found=new Set([s.p.y*SIZE+s.p.x]),queue=[{...s.p}];for(let j=0;j<queue.length;j++){const{x,y}=queue[j];for(const[dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dx,ny=y+dy,k=ny*SIZE+nx;if(nx>=0&&ny>=0&&nx<SIZE&&ny<SIZE&&s.map[k]&&!found.has(k)){found.add(k);queue.push({x:nx,y:ny})}}}assert.equal(found.size,s.map.filter(Boolean).length);assert.ok(found.has(s.stairs.y*SIZE+s.stairs.x));const all=[...s.items,...s.enemies,...s.traps,s.stairs,s.p].map(p=>p.y*SIZE+p.x);assert.equal(new Set(all).size,all.length);assert.ok(validSave(JSON.parse(JSON.stringify(s))))}});
function arena(){const s=createGame();s.map.fill(1);s.enemies=[];s.traps=[];s.items=[];s.p.x=10;s.p.y=10;return s}
test('wall and corner bump do not advance time',()=>{const s=arena();s.map[10*SIZE+11]=0;assert.equal(move(s,1,0),false);assert.equal(move(s,1,1),false);assert.equal(s.turn,0)});
test('moving attacks adjacent enemy and kill grants XP',()=>{const s=arena();s.enemies=[{x:11,y:10,hp:1,attack:4,type:'苔精',xp:12}];move(s,1,0);assert.equal(s.enemies.length,0);assert.equal(s.p.x,10);assert.equal(s.p.level,2);assert.equal(s.turn,1)});
test('enemies take one turn per player action',()=>{const s=arena();s.enemies=[{x:11,y:10,hp:50,attack:4,type:'苔精',xp:4}];move(s,0,0);assert.ok(s.p.hp<=32&&s.p.hp>=30);assert.equal(s.turn,1)});
test('items consume a turn, hunger progresses, starvation kills',()=>{const s=arena();s.p.hp=4;useItem(s,0);assert.equal(s.p.hp,28);assert.equal(s.bag.length,3);assert.equal(s.turn,1);for(let i=0;i<3;i++)move(s,0,0);assert.equal(s.p.food,99);s.p.food=0;s.p.hp=1;move(s,0,0);assert.equal(s.status,'dead');assert.equal(move(s,0,0),false)});
test('full bag leaves pickup, waiting after freeing slot picks up',()=>{const s=arena();s.bag=Array(12).fill('herb');s.items=[{x:11,y:10,type:'food'}];move(s,1,0);assert.equal(s.items.length,1);useItem(s,0);assert.equal(s.items.length,0);assert.equal(s.bag.length,12)});
test('stairs require position; tenth floor has victory',()=>{const s=arena();s.stairs={x:15,y:15};assert.equal(descend(s),false);s.p.x=15;s.p.y=15;assert.equal(descend(s),true);assert.equal(s.floor,2);s.floor=10;s.p.x=s.stairs.x;s.p.y=s.stairs.y;descend(s);assert.equal(s.status,'won');assert.equal(useItem(s,0),false)});
test('invalid save rejected',()=>{assert.equal(validSave(null),false);const s=createGame();s.bag=['bad'];assert.equal(validSave(s),false);s.bag=[];s.enemies=[{}];assert.equal(validSave(s),false)});
test('drop selected item without using it; one enemy turn and save roundtrip',()=>{const s=arena();s.p.hp=20;s.bag=['herb','food','scroll'];s.enemies=[{x:11,y:10,hp:30,attack:4,type:'苔精',xp:4}];assert.equal(dropItem(s,1),true);assert.deepEqual(s.bag,['herb','scroll']);assert.deepEqual(s.items,[{x:10,y:10,type:'food'}]);assert.equal(s.p.food,100);assert.equal(s.turn,1);assert.ok(s.p.hp>=14&&s.p.hp<=16);const restored=JSON.parse(JSON.stringify(s));assert.ok(validSave(restored));assert.deepEqual(restored.items,s.items);});
test('exchange with full bag preserves count and replaces exactly the selected slot',()=>{const s=arena();s.bag=Array(12).fill('herb');s.bag[7]='scroll';s.items=[{x:10,y:10,type:'warp'}];assert.equal(dropItem(s,7),true);assert.equal(s.bag.length,12);assert.equal(s.bag[7],'warp');assert.equal(s.bag.filter(i=>i==='herb').length,11);assert.deepEqual(s.items,[{x:10,y:10,type:'scroll'}]);assert.equal(s.turn,1);assert.ok(validSave(JSON.parse(JSON.stringify(s))));});
test('exchange also works with bag space and does not auto-pick the dropped item',()=>{const s=arena();s.bag=['food'];s.items=[{x:10,y:10,type:'herb'}];dropItem(s,0);assert.deepEqual(s.bag,['herb']);assert.equal(s.items[0].type,'food');assert.equal(s.items.length,1);});
test('dropped item can be picked back up by leaving and returning',()=>{const s=arena();s.bag=['scroll'];dropItem(s,0);move(s,1,0);assert.equal(s.items.length,1);move(s,-1,0);assert.deepEqual(s.bag,['scroll']);assert.equal(s.items.length,0);});
test('invalid drop and finished runs cannot mutate inventory or consume turns',()=>{for(const index of [-1,99,0.5,NaN]){const s=arena(),before=JSON.stringify(s);assert.equal(dropItem(s,index),false);assert.equal(JSON.stringify(s),before)}for(const status of ['dead','won']){const s=arena();s.status=status;const before=JSON.stringify(s);assert.equal(dropItem(s,0),false);assert.equal(JSON.stringify(s),before)}});
